server:
  port: 8003
spring:
  application: #服务名称
    name: consul-provider-payment
  cloud:
    consul: #consul地址
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

